#!/usr/bin/env php
<?php
// application.php

define('APP_PATH', __DIR__);

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}
if (
    (!$loader = includeIfExists(__DIR__.'/../vendor/autoload.php')) &&
    (!$loader = includeIfExists(__DIR__.'/../../autoload.php')) &&
    (!$loader = includeIfExists(__DIR__.'/../../../autoload.php')) &&
    (!$loader = includeIfExists(__DIR__.'/vendor/autoload.php'))
) {
    $msg = 'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL;
    fwrite(STDERR, $msg);
    exit(1);
}
require __DIR__.'/vendor/autoload.php';

use RedstoneTechnology\SiteBuild\Commands;
use RedstoneTechnology\SiteBuild\Application;

$templates = new League\Plates\Engine();
$theme = new RedstoneTechnology\SiteBuild\Utilities\Theme($templates);
$application = new Application();
$application->run();
