#!/usr/bin/env php
<?php
// application.php

define('APP_PATH', __DIR__);

require __DIR__.'/vendor/autoload.php';

use RedstoneTechnology\SiteBuild\Commands;
use RedstoneTechnology\SiteBuild\Application;

$templates = new League\Plates\Engine();
$theme = new RedstoneTechnology\SiteBuild\Utilities\Theme($templates);
$application = new Application();
$application->run();
